import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { HeaderWrapper } from "../component/HeaderWrapper";
import { sanityClient } from "@/lib/sanity";
import { HeaderProps } from "@/types";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
  const headerDataRaw: Partial<HeaderProps> | null = await sanityClient.fetch(`
    *[_type == "header"][0]{
      logo,
      menus[]{
        title,
        items[]{
          title,
          megaContent[]{
            links[]{title, url},
            featuredProduct{
              title,
              price,
              image
            }
          }
        }
      },
      rightLinks[]{title, url, icon}
    }
  `);

  const headerData: HeaderProps = {
    logo: headerDataRaw?.logo ?? null,
    menus: headerDataRaw?.menus ?? [],
    rightLinks: headerDataRaw?.rightLinks ?? [],
  };

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
           {/* Header */}
        <HeaderWrapper {...headerData} />
        {children}
      </body>
    </html>
  );
}
