import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { HeaderWrapper } from "../component/HeaderWrapper";
import { Footer } from "../component/Footer";

// Popup import
import Popup from "../component/Popup";

// Queries
import { sanityClient } from "@/lib/sanity";
import { HeaderProps } from "@/types";
import { getFooter } from "../sanity/queries/getFooter";
import { getPopup } from "../sanity/queries/getPopup";  // <-- popup query import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // === Fetch Header Data ===
  const headerDataRaw: Partial<HeaderProps> | null = await sanityClient.fetch(`
    *[_type == "header"][0]{
      "logo": logo.asset->url,
      menus[] {
        title,
        url,                      
        items[] {
          title,
          megaContent[] {
            links[] { title, url },
            featuredProduct {
              title,
              price,
              image
            }
          }
        }
      },
      rightLinks[] { title, url, icon }
    }
  `);

  const headerData: HeaderProps = {
    logo: headerDataRaw?.logo ?? null,
    menus: headerDataRaw?.menus ?? [],
    rightLinks: headerDataRaw?.rightLinks ?? [],
  };

  // === Fetch Footer Data ===
  const footerData = await getFooter();

  // === Fetch Popup Data ===
  const popupData = await getPopup(); // <-- popup query

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        {/* Global Header */}
        <HeaderWrapper {...headerData} />

        {/* Page Content */}
        {children}

        {/* Global Footer */}
        <Footer data={footerData} />

        {/* Newsletter Popup */}
        {popupData && <Popup data={popupData} />}  {/* <-- render popup */}

      </body>
    </html>
  );
}
